[Bar0]
Meter=Shape
MeterStyle=BarStyle
Shape=Rectangle 0,(-3*100*[cBand0]-8/2),8,((4*100)*[cBand0]+8),(8/2)|Extend BarDecora
[Bar1]
Meter=Shape
MeterStyle=BarStyle
Shape=Rectangle 0,(-3*100*[cBand1]-8/2),8,((4*100)*[cBand1]+8),(8/2)|Extend BarDecora
[Bar2]
Meter=Shape
MeterStyle=BarStyle
Shape=Rectangle 0,(-3*100*[cBand2]-8/2),8,((4*100)*[cBand2]+8),(8/2)|Extend BarDecora
[Bar3]
Meter=Shape
MeterStyle=BarStyle
Shape=Rectangle 0,(-3*100*[cBand3]-8/2),8,((4*100)*[cBand3]+8),(8/2)|Extend BarDecora
[Bar4]
Meter=Shape
MeterStyle=BarStyle
Shape=Rectangle 0,(-3*100*[cBand4]-8/2),8,((4*100)*[cBand4]+8),(8/2)|Extend BarDecora
[Bar5]
Meter=Shape
MeterStyle=BarStyle
Shape=Rectangle 0,(-3*100*[cBand5]-8/2),8,((4*100)*[cBand5]+8),(8/2)|Extend BarDecora
[Bar6]
Meter=Shape
MeterStyle=BarStyle
Shape=Rectangle 0,(-3*100*[cBand6]-8/2),8,((4*100)*[cBand6]+8),(8/2)|Extend BarDecora
[Bar7]
Meter=Shape
MeterStyle=BarStyle
Shape=Rectangle 0,(-3*100*[cBand7]-8/2),8,((4*100)*[cBand7]+8),(8/2)|Extend BarDecora
[Bar8]
Meter=Shape
MeterStyle=BarStyle
Shape=Rectangle 0,(-3*100*[cBand8]-8/2),8,((4*100)*[cBand8]+8),(8/2)|Extend BarDecora
[Bar9]
Meter=Shape
MeterStyle=BarStyle
Shape=Rectangle 0,(-3*100*[cBand9]-8/2),8,((4*100)*[cBand9]+8),(8/2)|Extend BarDecora
[Bar10]
Meter=Shape
MeterStyle=BarStyle
Shape=Rectangle 0,(-3*100*[cBand10]-8/2),8,((4*100)*[cBand10]+8),(8/2)|Extend BarDecora
[Bar11]
Meter=Shape
MeterStyle=BarStyle
Shape=Rectangle 0,(-3*100*[cBand11]-8/2),8,((4*100)*[cBand11]+8),(8/2)|Extend BarDecora
[Bar12]
Meter=Shape
MeterStyle=BarStyle
Shape=Rectangle 0,(-3*100*[cBand12]-8/2),8,((4*100)*[cBand12]+8),(8/2)|Extend BarDecora
[Bar13]
Meter=Shape
MeterStyle=BarStyle
Shape=Rectangle 0,(-3*100*[cBand13]-8/2),8,((4*100)*[cBand13]+8),(8/2)|Extend BarDecora
[Bar14]
Meter=Shape
MeterStyle=BarStyle
Shape=Rectangle 0,(-3*100*[cBand14]-8/2),8,((4*100)*[cBand14]+8),(8/2)|Extend BarDecora
[Bar15]
Meter=Shape
MeterStyle=BarStyle
Shape=Rectangle 0,(-3*100*[cBand15]-8/2),8,((4*100)*[cBand15]+8),(8/2)|Extend BarDecora
[Bar16]
Meter=Shape
MeterStyle=BarStyle
Shape=Rectangle 0,(-3*100*[cBand16]-8/2),8,((4*100)*[cBand16]+8),(8/2)|Extend BarDecora
[Bar17]
Meter=Shape
MeterStyle=BarStyle
Shape=Rectangle 0,(-3*100*[cBand17]-8/2),8,((4*100)*[cBand17]+8),(8/2)|Extend BarDecora
[Bar18]
Meter=Shape
MeterStyle=BarStyle
Shape=Rectangle 0,(-3*100*[cBand18]-8/2),8,((4*100)*[cBand18]+8),(8/2)|Extend BarDecora
[Bar19]
Meter=Shape
MeterStyle=BarStyle
Shape=Rectangle 0,(-3*100*[cBand19]-8/2),8,((4*100)*[cBand19]+8),(8/2)|Extend BarDecora
[Bar20]
Meter=Shape
MeterStyle=BarStyle
Shape=Rectangle 0,(-3*100*[cBand20]-8/2),8,((4*100)*[cBand20]+8),(8/2)|Extend BarDecora
[Bar21]
Meter=Shape
MeterStyle=BarStyle
Shape=Rectangle 0,(-3*100*[cBand21]-8/2),8,((4*100)*[cBand21]+8),(8/2)|Extend BarDecora
[Bar22]
Meter=Shape
MeterStyle=BarStyle
Shape=Rectangle 0,(-3*100*[cBand22]-8/2),8,((4*100)*[cBand22]+8),(8/2)|Extend BarDecora
[Bar23]
Meter=Shape
MeterStyle=BarStyle
Shape=Rectangle 0,(-3*100*[cBand23]-8/2),8,((4*100)*[cBand23]+8),(8/2)|Extend BarDecora
[Bar24]
Meter=Shape
MeterStyle=BarStyle
Shape=Rectangle 0,(-3*100*[cBand24]-8/2),8,((4*100)*[cBand24]+8),(8/2)|Extend BarDecora
[Bar25]
Meter=Shape
MeterStyle=BarStyle
Shape=Rectangle 0,(-3*100*[cBand25]-8/2),8,((4*100)*[cBand25]+8),(8/2)|Extend BarDecora
[Bar26]
Meter=Shape
MeterStyle=BarStyle
Shape=Rectangle 0,(-3*100*[cBand26]-8/2),8,((4*100)*[cBand26]+8),(8/2)|Extend BarDecora
[Bar27]
Meter=Shape
MeterStyle=BarStyle
Shape=Rectangle 0,(-3*100*[cBand27]-8/2),8,((4*100)*[cBand27]+8),(8/2)|Extend BarDecora
[Bar28]
Meter=Shape
MeterStyle=BarStyle
Shape=Rectangle 0,(-3*100*[cBand28]-8/2),8,((4*100)*[cBand28]+8),(8/2)|Extend BarDecora
[Bar29]
Meter=Shape
MeterStyle=BarStyle
Shape=Rectangle 0,(-3*100*[cBand29]-8/2),8,((4*100)*[cBand29]+8),(8/2)|Extend BarDecora
[Bar30]
Meter=Shape
MeterStyle=BarStyle
Shape=Rectangle 0,(-3*100*[cBand30]-8/2),8,((4*100)*[cBand30]+8),(8/2)|Extend BarDecora
[Bar31]
Meter=Shape
MeterStyle=BarStyle
Shape=Rectangle 0,(-3*100*[cBand31]-8/2),8,((4*100)*[cBand31]+8),(8/2)|Extend BarDecora
[Bar32]
Meter=Shape
MeterStyle=BarStyle
Shape=Rectangle 0,(-3*100*[cBand32]-8/2),8,((4*100)*[cBand32]+8),(8/2)|Extend BarDecora
[Bar33]
Meter=Shape
MeterStyle=BarStyle
Shape=Rectangle 0,(-3*100*[cBand33]-8/2),8,((4*100)*[cBand33]+8),(8/2)|Extend BarDecora
[Bar34]
Meter=Shape
MeterStyle=BarStyle
Shape=Rectangle 0,(-3*100*[cBand34]-8/2),8,((4*100)*[cBand34]+8),(8/2)|Extend BarDecora
[Bar35]
Meter=Shape
MeterStyle=BarStyle
Shape=Rectangle 0,(-3*100*[cBand35]-8/2),8,((4*100)*[cBand35]+8),(8/2)|Extend BarDecora
[Bar36]
Meter=Shape
MeterStyle=BarStyle
Shape=Rectangle 0,(-3*100*[cBand36]-8/2),8,((4*100)*[cBand36]+8),(8/2)|Extend BarDecora