[Variables]

;------------------------ CPU

Sys_CPUOpt_IfDisabled=1

Sys_CPU_SensorId=0xf0000300
Sys_CPU_SensorInstance=0x0
Sys_CPU_EntryID=0x7000009

Sys_CPUTemp_SensorId=0xf0000400
Sys_CPUTemp_SensorInstance=0x0
Sys_CPUTemp_EntryID=0x100007e

Sys_CPUOpt1_SensorId=0xf0000300
Sys_CPUOpt1_SensorInstance=0x0
Sys_CPUOpt1_EntryID=0x6000000
Sys_CPUOpt1_Label=核心频率
Sys_CPUOpt1_Unit=MHz
Sys_CPUOpt1_Decimals=

Sys_CPUOpt2_SensorId=0xf0002a00
Sys_CPUOpt2_SensorInstance=0x0
Sys_CPUOpt2_EntryID=0x5000000
Sys_CPUOpt2_Label=当前功耗
Sys_CPUOpt2_Unit=W
Sys_CPUOpt2_Decimals=3

Sys_CPUOpt3_SensorId=0xf0ec0502
Sys_CPUOpt3_SensorInstance=0x0
Sys_CPUOpt3_EntryID=0x3000003
Sys_CPUOpt3_Label=冷排转速
Sys_CPUOpt3_Unit=RPM
Sys_CPUOpt3_Decimals=

Sys_CPUOpt4_SensorId=0xf0ec0502
Sys_CPUOpt4_SensorInstance=0x0
Sys_CPUOpt4_EntryID=0x1000001
Sys_CPUOpt4_Label=水道温度
Sys_CPUOpt4_Unit=°C
Sys_CPUOpt4_Decimals=1

;------------------------ GPU

Sys_GPUOpt_IfDisabled=1

Sys_GPU_SensorId=0xe0002000
Sys_GPU_SensorInstance=0x14
Sys_GPU_EntryID=0x7000000

Sys_GPUTemp_SensorId=0xe0002000
Sys_GPUTemp_SensorInstance=0x14
Sys_GPUTemp_EntryID=0x1000000

Sys_GPUOpt1_SensorId=0xf0ec0502
Sys_GPUOpt1_SensorInstance=0x0
Sys_GPUOpt1_EntryID=0x3000004
Sys_GPUOpt1_Label=冷排转速
Sys_GPUOpt1_Unit=RPM
Sys_GPUOpt1_Decimals=

Sys_GPUOpt2_SensorId=0xf0ec0502
Sys_GPUOpt2_SensorInstance=0x0
Sys_GPUOpt2_EntryID=0x1000002
Sys_GPUOpt2_Label=水道温度
Sys_GPUOpt2_Unit=°C
Sys_GPUOpt2_Decimals=1

;------------------------ RAM

Sys_RAMUsage_SensorId=0xf0000301
Sys_RAMUsage_SensorInstance=0x0
Sys_RAMUsage_EntryID=0x8000005

Sys_RAMUsed_SensorId=0xf0000301
Sys_RAMUsed_SensorInstance=0x0
Sys_RAMUsed_EntryID=0x8000003

Sys_RAMFree_SensorId=0xf0000301
Sys_RAMFree_SensorInstance=0x0
Sys_RAMFree_EntryID=0x8000004

Sys_SWAPUsage_SensorId=0xf0000301
Sys_SWAPUsage_SensorInstance=0x0
Sys_SWAPUsage_EntryID=0x8000002

Sys_SWAPCommitted_SensorId=0xf0000301
Sys_SWAPCommitted_SensorInstance=0x0
Sys_SWAPCommitted_EntryID=0x8000000

Sys_SWAPFree_SensorId=0xf0000301
Sys_SWAPFree_SensorInstance=0x0
Sys_SWAPFree_EntryID=0x8000001

