
[MusicCtrlStyle]
AntiAlias=1
Hidden=1
Group=Music
ButtonImage=#IMG##CurrentSection#
DynamicVariables=1
LeftMouseUpAction=!CommandMeasure Player #CurrentSection#

[MusicInfoStyle]
FontFace=#MusicFace#
AntiAlias=1
StringAlign=Center
X=(410/2)

[SCoverStyle]
MaskImageName=#IMG#Cover
X=([NoCoverBG:W]/2-147/2)
Y=34
W=147
H=147

[ProgressStyle]
W=410
H=4
Y=266

[PDStyle]
FontFace=#MusicFace#
StringStyle=Bold
AntiAlias=1
FontSize=8
FontColor=#FontColor3#
Y=245
Hidden=1
Group=Music
