[Variables]

CircleColor1=250,195,50
CircleIcon1=#@#Images\FlatIcons\C.png
CirclePath1=

CircleColor2=240,80,90
CircleIcon2=#@#Images\FlatIcons\M.png
CirclePath2=

CircleColor3=200,200,200
CircleIcon3=#@#Images\FlatIcons\H.png
CirclePath3=

CircleColor4=20,180,210
CircleIcon4=#@#Images\FlatIcons\T.png
CirclePath4=

CircleColor5=20,200,140
CircleIcon5=#@#Images\FlatIcons\C.png
CirclePath5=

CircleColor6=190,165,100
CircleIcon6=#@#Images\FlatIcons\Y.png
CirclePath6=

CircleColor7=120,110,200
CircleIcon7=#@#Images\FlatIcons\Z.png
CirclePath7=

CircleColor8=10,170,150
CircleIcon8=#@#Images\FlatIcons\N.png
CirclePath8=

CircleColor9=130,90,60
CircleIcon9=#@#Images\FlatIcons\F.png
CirclePath9=
