[Variables]
SkinWidth=1920
ComponentSize=M
Language=zh-CN
SendNotice=1
UseAlarm=0

TypeNet=0
ExplorerPath=shell:Appsfolder\Microsoft.MicrosoftEdge_8wekyb3d8bbwe!MicrosoftEdge
ExplorerIcon=f282
ExplorerColor=0,120,215
TimeFormat=%H
RecycleMaxCount=100
RecycleMaxSize=1073741824
UserName=%USERNAME%
UserPortrait=%USERPROFILE%\AppData\Local\Temp\%USERNAME%.bmp

TypeMusic=1
PlayerType=MusicPlayer
PlayerName=CloudMusic
PlayerPath=C:\Program Files (x86)\Netease\CloudMusic\cloudmusic.exe
PlayerLabel=CloudMusic
OridinalWallpaper=C:\Users\11418\Documents\Rainmeter\Skins\SAO Augma\@Resources\Images\Default\OrdinalBG.png

TypeCalendar=Double
TypePicture=Album
TypeSystem=Windows
TypeSchedule=Note
WeatherCode=
AppKey=
Sign=
MonthName=
; MonthName=Jan.|Feb.|Mar.|Apr.|May.|Jun.|Jul.|Aug.|Sep.|Oct.|Nov.|Dec.
PicturePath=#@#Images\Default\Default.jpg
AlbumPath=#@#Images\Default
PictureMode=1
PictureTitle=
PictureStayTime=20
ViewPath=#@#Tutorial
ViewExtensions=
SystemTitle=
ScheduleTitle=
NoteTitle=

CompunentSize=M
