[Variables]
SizeBottom_Net_F1=15
SizeBottom_Net_F2=20
SizeTop_Time_F=21

SizeMain_Offset=1
SizeMain_F1=25
SizeMain_F2=28

SizeRecycle_XOffset=0
SizeRecycle_YOffset=0
SizeOption_XOffset=0
SizeOption_YOffset=2
SizeButton_F1=20
SizeButton_F2=25
SizeOption_MenuF=14
SizeModule_F=13

SizePlayer_F1=12
SizePlayer_F2=22
SizePlayer_LXOffset=2
SizePlayer_LYOffset=2
SizePlayer_SXOffset=1
SizePlayer_SYOffset=1
SizePlayer_TextF=15

SizeUser_F=35

SizeCompo_F1=42
SizeCompo_F2=50

