[Bool2]
Meter=Shape
Y=((70+30*1)*#Scale#)
MeterStyle=Stroke:S
[Line2]
Meter=String
MeterStyle=String:S | Note:S
[Bool3]
Meter=Shape
Y=((70+30*2)*#Scale#)
MeterStyle=Stroke:S
[Line3]
Meter=String
MeterStyle=String:S | Note:S
[Bool4]
Meter=Shape
Y=((70+30*3)*#Scale#)
Shape=Line 0,(25*#scale#),(#W#-#P#*2),(25*#scale#) | StrokeWidth 0
MeterStyle=Stroke:S
[Line4]
Meter=String
MeterStyle=String:S | Note:S
